version: 2

install: &install
  run:
    name: Install mkdocs and markdown extensions
    command: pip install -r .circleci/requirements.txt

jobs:
  install-mkdocs-deps:
    docker:
      - image: python:3.8.2
    steps:
      - checkout
      - *install
      - add_ssh_keys:
          fingerprints:
            - "68:04:73:e0:77:a8:4e:57:eb:ad:8e:25:9e:1c:23:30"
      - run:
          name: Deploy new pages
          command: mkdocs gh-deploy -c -v

workflows:
   version: 2
   pipeline:
       jobs:
           - install-mkdocs-deps:
               filters:
                    branches:
                        only: main
