version: 2

install: &install
  run:
    name: Install mkdocs and markdown extensions
    command: pip install -r .circleci/requirements.txt

jobs:
  install-mkdocs-deps:
    docker:
      - image: python:3.8.2
    steps:
      - checkout
      - *install
      - add_ssh_keys:
          fingerprints:
            - "cb:29:a0:8f:cf:b1:72:07:5d:eb:ac:16:34:4a:4e:f8"
      - run:
          name: Deploy new pages
          command: mkdocs gh-deploy -c -v

workflows:
   version: 2
   pipeline:
       jobs:
           - install-mkdocs-deps:
               filters:
                    branches:
                        only: main
